"""
RPAステップの説明文定義
各ステップの動作や用途について詳細な説明を提供
"""

# ステップ説明の辞書
STEP_DESCRIPTIONS = {
    "abort": "シナリオの実行を強制終了します。エラー発生時や条件を満たさない場合の処理中断に使用します。",
    "add-memo": "処理にメモやコメントを追加します。デバッグや保守のための情報記録に使用します。",
    "align-focused-window": "最前面のウィンドウを画面の指定位置（左、右、中央など）に配置します。",
    "api-web": "Web APIを呼び出してデータを取得・送信します。",
    "assign-arithmetic-result-to-string-variable-v2": "数値の四則演算結果を変数に格納します。計算処理に使用します。",
    "assign-clipboard-to-string-variable": "クリップボードの内容を変数に格納します。コピーしたデータの取得に使用します。",
    "assign-date-business-to-string-variable": "営業日を考慮した日付を計算して変数に格納します。",
    "assign-date-calculation-to-string-variable": "日付の加算・減算を行い、結果を変数に格納します。",
    "assign-date-to-string-variable": "現在日付または指定日付を指定フォーマットで変数に格納します。日付処理に使用します。",
    "assign-date-weekdays-to-string-variable": "指定した曜日の日付を計算して変数に格納します。",
    "assign-day-of-week-to-string-variable": "指定日付の曜日を取得して変数に格納します。",
    "assign-environment-variable": "環境変数の値を取得して変数に格納します。システム情報の取得に使用します。",
    "assign-file-modification-timestamp-to-string-variable": "ファイルの更新日時を取得して変数に格納します。ファイル管理に使用します。",
    "assign-file-size-to-string-variable": "ファイルサイズを取得して変数に格納します。ファイル容量の確認に使用します。",
    "assign-live-input-to-string-variable": "実行時にユーザーから入力を受け取り、変数に格納します。動的な値の入力に使用します。",
    "assign-password-variable": "パスワードを暗号化して変数に格納します。セキュアな認証情報の管理に使用します。",
    "assign-random-number-to-string-variable": "指定範囲の乱数を生成して変数に格納します。ランダムな値が必要な処理に使用します。",
    "assign-string-variable": "文字列データを変数に格納します。後続の処理で参照可能なデータの保存に使用します。",
    "assign-time-calculation-to-string-variable": "時刻の計算結果を変数に格納します。",
    "assign-timestamp-to-string-variable": "現在時刻を指定フォーマットで変数に格納します。",
    "break-loop": "ループを抜けます。",
    "calculate-excel-column": "列番号の計算（加算・減算）を行います。動的な列参照に使用します。",
    "change-speed-for-command-execution": "以降のコマンド実行間の待機時間を変更します。処理速度の調整が必要な場合に使用します。",
    "check-for-errors": "直前のコマンドのエラーを確認し、エラー処理を実行します。リトライ設定も可能です。",
    "check-for-errors-2": "エラー確認と処理を行い、リトライ前の事前処理を実行できます。",
    "check-html-checkbox-or-radiobutton": "チェックボックスまたはラジオボタンの状態を確認し、処理を分岐します。",
    "check-json-type": "JSONデータの型を確認し、結果により処理を分岐します。",
    "click-html-alert": "JavaScriptアラートをクリックして閉じます。",
    "click-html-element": "HTML要素をクリックします。",
    "click-mouse": "現在のマウス位置でクリック（シングル、ダブル、右クリック）を実行します。",
    "click-uia-element": "UIオートメーション要素をクリックします。",
    "close-browser": "ブラウザを閉じます。",
    "close-excel-book": "Excelブックを閉じます。",
    "compare-dates-and-branch": "日付を比較し、結果により処理を分岐します。",
    "compare-numbers-and-branch": "数値を比較し、結果により処理を分岐します。",
    "compare-strings-and-branch": "文字列を比較し、結果により処理を分岐します。",
    "compress-file-or-directory": "ファイルまたはフォルダを圧縮してアーカイブを作成します。",
    "continue-loop": "ループの先頭に戻ります。",
    "convert-character-type": "全角・半角文字の変換を行います。文字種の統一に使用します。",
    "convert-date-format": "日付の表示形式を変換します。異なるシステム間の日付形式統一に使用します。",
    "copy-excel-range": "セル範囲をクリップボードにコピーします。",
    "copy-file-or-directory": "ファイルまたはフォルダをコピーします。",
    "copy-paste-spreadsheet": "スプレッドシートの範囲をコピーして貼り付けます。",
    "copy-spreadsheet-sheet": "スプレッドシートのシートをコピーします。",
    "copy-to-clipboard": "指定した文字列をクリップボードにコピーします。他アプリケーションへのデータ受け渡しに使用します。",
    "create-directory": "フォルダを作成します。",
    "create-excel-sheet": "新しいワークシートを作成します。",
    "create-spreadsheet": "Googleスプレッドシートなどのクラウドベースのスプレッドシートを作成します。",
    "create-spreadsheet-sheet": "スプレッドシートに新しいシートを作成します。",
    "decompress-file": "圧縮ファイルを解凍します。",
    "delete-excel-range": "指定範囲のセルを削除し、周囲のセルをシフトします。",
    "delete-excel-sheet": "ワークシートを削除します。",
    "delete-file-or-directory": "ファイルまたはフォルダを削除します。",
    "delete-spreadsheet": "Googleスプレッドシートを削除します。",
    "delete-spreadsheet-range": "スプレッドシートの指定範囲を削除します。",
    "delete-spreadsheet-sheet": "スプレッドシートのシートを削除します。",
    "download-html-csv": "HTML上の表をCSV形式でダウンロードします。",
    "download-html-element": "HTML上の画像をダウンロードします。",
    "drag-and-drop-to-absolute-coordinates": "現在位置から指定した絶対座標までドラッグ＆ドロップを実行します。",
    "drag-and-drop-to-image": "画像認識を使用して、現在位置から画像の位置までドラッグ＆ドロップを実行します。",
    "drag-and-drop-to-relative-coordinates": "現在位置から相対的な位置までドラッグ＆ドロップを実行します。",
    "escape-html-iframe": "iframeから抜け出します。",
    "extract-fname": "ファイルパスからファイル名やフォルダ名を抽出します。パス処理に使用します。",
    "find-image-and-branch": "画像を探し、結果により処理を分岐します。",
    "find-newest-file-from-fixed-directory": "指定ディレクトリから最新のファイルやフォルダを検索します。最新データの処理に使用します。",
    "focus-html-element": "HTML要素にフォーカスを当てます。",
    "focus-window": "記憶したウィンドウを最前面に表示します。複数ウィンドウ間の切り替えに使用します。",
    "focus-window-by-name": "ウィンドウ名を指定して該当するウィンドウを最前面に表示します。",
    "get-excel-address": "選択セルのアドレス（A1形式またはR1C1形式）を取得します。",
    "get-excel-last-column": "データが入力されている最終列を取得します。特定行の最終列も取得可能です。",
    "get-excel-last-row": "データが入力されている最終行を取得します。特定列の最終行も取得可能です。",
    "get-excel-sheet-name": "現在のワークシート名を取得します。",
    "get-excel-values": "セル範囲の値を取得します。書式付きまたは値のみを選択可能です。",
    "get-json-values": "JSONデータから値を取得します。",
    "get-spreadsheet-last-row": "スプレッドシートのデータ最終行を取得します。",
    "get-spreadsheet-sheet-name": "アクティブなスプレッドシートのシート名を取得します。",
    "get-spreadsheet-url": "スプレッドシートのURLを取得します。",
    "get-spreadsheet-values": "スプレッドシートのセル値を取得します。",
    "get-text-from-uia-element": "UIオートメーション要素からテキストを取得します。",
    "get-uia-element-clickable-point": "UIオートメーション要素のクリック可能な座標を取得します。",
    "get-window-title": "現在のウィンドウまたは指定したウィンドウのタイトルを取得し、変数に格納します。",
    "group-commands": "複数のコマンドをグループ化して管理します。",
    "inherit-browsers": "親シナリオからブラウザ情報を継承します。",
    "inherit-excel": "親シナリオからExcel情報を継承します。",
    "inherit-passwords": "親シナリオからパスワードを継承します。",
    "inherit-variables": "親シナリオから変数を継承します。",
    "inherit-windows": "親シナリオからウィンドウ情報を継承します。",
    "insert-excel-range": "指定範囲にセルを挿入し、既存のセルをシフトします。",
    "insert-spreadsheet-range": "スプレッドシートに行や列を挿入します。",
    "loop-by-line": "テキストを1行ずつループ処理します。",
    "loop-csv": "CSVファイルを読み込んでループ処理します。",
    "loop-directory-contents": "フォルダ内のファイルをループ処理します。",
    "loop-excel-col": "Excelの列をループ処理します。",
    "loop-excel-row": "Excelの行をループ処理します。",
    "loop-n-times": "指定回数だけループ処理を実行します。",
    "loop-spreadsheet-col": "スプレッドシートの列をループ処理します。",
    "loop-spreadsheet-row": "スプレッドシートの行をループ処理します。",
    "maximize-focused-window": "最前面のウィンドウを最大化、最小化、または元のサイズに戻します。",
    "move-excel-sheet": "ワークシートを移動またはコピーします。別ブックへの移動も可能です。",
    "move-fixed-file-to-fixed-directory": "ファイルを別のフォルダに移動します。",
    "move-mouse-to-absolute-coordinates": "マウスカーソルを画面上の絶対座標に移動します。オプションでクリックも実行できます。",
    "move-mouse-to-image": "画像認識を使用して指定した画像の位置にマウスを移動します。動的な要素のクリックに使用します。",
    "move-mouse-to-relative-coordinates": "マウスカーソルを現在位置から相対的に移動します。微調整が必要な場合に使用します。",
    "move-spreadsheet-sheet": "スプレッドシートのシート位置を移動します。",
    "offset-excel-range": "選択範囲を指定した分だけ移動します。",
    "open-fixed-directory-name": "指定したフォルダをエクスプローラで開きます。",
    "open-static-file-name": "指定したファイルを関連付けられたアプリケーションで開きます。",
    "parse-brackets": "文字列から括弧や引用符で囲まれた部分を抽出します。データの解析に使用します。",
    "parse-break-and-space": "文字列から改行や空白を削除します。テキストの整形に使用します。",
    "parse-delimiters": "区切り文字で分割された文字列から特定の要素を抽出します。CSV処理などに使用します。",
    "parse-regex": "正規表現にマッチする文字列を抽出します。高度なテキスト処理に使用します。",
    "paste-excel-range": "クリップボードからセル範囲に貼り付けます。形式を指定可能です。",
    "pause": "指定した秒数だけ処理を一時停止します。画面の描画完了やシステムの応答を待つ際に使用します。",
    "pause-and-ask-to-proceed": "メッセージを表示して一時停止し、ユーザーの確認を待ちます。重要な処理の前に確認を取る際に使用します。",
    "pause-and-countdown-to-proceed": "指定時間のカウントダウン後に自動的に処理を継続します。ユーザーに準備時間を与える際に使用します。",
    "play-sound": "通知音を再生します。処理完了の通知に使用します。",
    "prepend-date-to-variable-filename": "ファイル名の先頭に日付を追加します。",
    "prepend-string-to-variable-filename": "ファイル名の先頭に文字列を追加します。",
    "prepend-variable-to-file": "ファイル名の先頭に変数の値を追加します。",
    "raise-error": "意図的にエラーを発生させます。エラーハンドリングのテストや条件分岐での使用を想定しています。",
    "read-file": "テキストファイルの内容を読み込み、変数に格納します。",
    "receive-emails": "メールを受信してループ処理します。",
    "receive-emails-gmail": "Gmailからメールを受信してループ処理します。",
    "receive-emails-microsoft": "Microsoftからメールを受信してループ処理します。",
    "remember-focused-browser-window": "現在のブラウザウィンドウを記憶します。",
    "remember-focused-window": "現在最前面に表示されているウィンドウの参照を変数に記憶し、後で切り替えや操作に使用できます。",
    "remember-named-window": "指定した名前を含むウィンドウを検索して記憶します。複数のウィンドウを扱う際の識別に使用します。",
    "remember-open-excel-book": "開いているExcelブックを変数に記憶します。複数ブック操作時に使用します。",
    "remember-spreadsheet": "remember-spreadsheetの処理を実行します。",
    "rename-excel-sheet": "ワークシートの名前を変更します。",
    "rename-file-or-directory": "ファイルまたはフォルダの名前を変更します。",
    "rename-spreadsheet": "rename-spreadsheetの処理を実行します。",
    "rename-spreadsheet-sheet": "スプレッドシートのシート名を変更します。",
    "replace-strings": "文字列内の特定の文字を置換します。テキストの変換に使用します。",
    "retrieve-attribute-of-html-element": "HTML要素の属性値を取得します。",
    "retrieve-link-of-html-element": "HTML要素のリンクURLを取得します。",
    "retrieve-src-of-html-element": "画像要素のソースURLを取得します。",
    "retrieve-text-of-html-alert": "JavaScriptアラートのメッセージを取得します。",
    "retrieve-text-of-html-element": "HTML要素のテキストを取得します。",
    "run-browser": "ブラウザを起動します。",
    "run-browser-with-profile": "ユーザープロファイルを指定してブラウザを起動します。",
    "run-excel": "Excelファイルを開きます。パスワード保護されたファイルにも対応します。",
    "run-excel-macro": "VBAマクロを実行します。引数の渡しも可能です。",
    "run-executable": "指定したアプリケーションやファイルを起動します。パスや引数、ウィンドウ表示状態を設定できます。",
    "run-executable-and-wait": "アプリケーションを起動し、そのプロセスが終了するまで待機します。実行結果を変数に格納できます。",
    "run-external-scenario-and-branch": "別のシナリオを実行し、結果により処理を分岐します。",
    "run-javascript-in-browser": "ブラウザ上でJavaScriptを実行します。",
    "save-excel-book": "Excelブックを保存します。",
    "scroll-mouse": "マウスホイールを使用して上下にスクロールします。ページや文書の移動に使用します。",
    "search-file-from-directory-and-branch": "ファイルやフォルダの存在を確認し、結果により処理を分岐します。",
    "search-html-element-and-branch": "HTML要素の出現を待ち、結果により処理を分岐します。",
    "search-screen-and-branch": "画像が画面に表示されるまで待機し、結果によって処理を分岐します。",
    "select-excel-range": "セル範囲を選択します。",
    "send-email": "メールを送信します。",
    "send-email-gmail": "Gmail経由でメールを送信します。",
    "send-email-microsoft": "Microsoft経由でメールを送信します。",
    "send-password-to-html-element": "HTML要素にパスワードを安全に入力します。",
    "send-password-to-uia-element": "UIオートメーション要素にパスワードを入力します。",
    "send-text-to-html-element": "HTML要素にテキストを入力します。",
    "send-text-to-uia-element": "UIオートメーション要素にテキストを入力します。",
    "set-browser-cookie": "ブラウザにCookieを設定します。",
    "set-dropdown-html-element": "ドロップダウンリストの値を選択します。",
    "set-excel-values": "セル範囲に値を設定します。配列データの一括入力も可能です。",
    "set-spreadsheet-values": "スプレッドシートのセルに値を設定します。",
    "switch-excel-sheet": "アクティブなワークシートを切り替えます。",
    "switch-html-iframe": "iframeに切り替えます。",
    "take-screenshot": "画面全体または指定範囲のスクリーンショットを撮影し、ファイルに保存します。記録や証跡保存に使用します。",
    "type-hotkeys": "複数のキーを組み合わせたショートカットキーを入力します。Ctrl+C、Alt+Tab などに使用します。",
    "type-html-hotkeys": "HTML上でショートカットキーを入力します。",
    "typewrite-all-string": "文字列を貼り付け操作で一括入力します。大量のテキスト入力を高速に行う際に使用します。",
    "typewrite-password": "パスワードを安全に入力します。入力値は暗号化され、ログに残りません。",
    "typewrite-static-string": "指定した文字列を一文字ずつキーボード入力します。フォームへの入力に使用します。",
    "visit-url": "指定したURLにアクセスします。",
    "visit-url-with-basic-auth": "Basic認証付きでURLにアクセスします。",
    "write-file": "テキストファイルに文字列を書き込みます。",
}


def get_description(cmd: str) -> str:
    """
    コマンド名から説明文を取得

    Args:
        cmd: コマンド名

    Returns:
        説明文（見つからない場合は空文字列）
    """
    return STEP_DESCRIPTIONS.get(cmd, "")