"""
RPAステップのタグ定義
各ステップの機能カテゴリーや用途を示すタグを提供
"""

# ステップタグの辞書
STEP_TAGS = {
    "abort": ["制御", "エラー処理", "終了"],
    "add_memo": ["ドキュメント", "デバッグ", "保守"],
    "align_focused_window": ["ウィンドウ", "UI操作", "配置"],
    "api_web": ["API", "データ連携", "Web"],
    "assign_arithmetic_result_to_string_variable_v2": ["変数", "計算", "数値処理"],
    "assign_clipboard_to_string_variable": ["変数", "クリップボード", "データ取得"],
    "assign_date_business_to_string_variable": ["変数", "日付", "営業日"],
    "assign_date_calculation_to_string_variable": ["変数", "日付", "計算"],
    "assign_date_to_string_variable": ["変数", "日付", "フォーマット"],
    "assign_date_weekdays_to_string_variable": ["変数", "日付", "曜日"],
    "assign_day_of_week_to_string_variable": ["変数", "日付", "曜日"],
    "assign_environment_variable": ["変数", "環境", "システム情報"],
    "assign_file_modification_timestamp_to_string_variable": ["変数", "ファイル", "タイムスタンプ"],
    "assign_file_size_to_string_variable": ["変数", "ファイル", "サイズ"],
    "assign_live_input_to_string_variable": ["変数", "入力", "インタラクティブ"],
    "assign_password_variable": ["変数", "セキュリティ", "パスワード"],
    "assign_random_number_to_string_variable": ["変数", "ランダム", "数値処理"],
    "assign_string_variable": ["変数", "基本", "データ保存"],
    "assign_time_calculation_to_string_variable": ["変数", "時刻", "計算"],
    "assign_timestamp_to_string_variable": ["変数", "時刻", "フォーマット"],
    "break_loop": ["ループ", "制御", "脱出"],
    "calculate_excel_column": ["Excel", "計算", "列操作"],
    "change_speed_for_command_execution": ["制御", "速度調整", "待機"],
    "check_for_errors": ["エラー処理", "制御", "リトライ"],
    "check_for_errors_2": ["エラー処理", "制御", "リトライ"],
    "check_html_checkbox_or_radiobutton": ["HTML", "フォーム", "状態確認"],
    "check_json_type": ["JSON", "データ処理", "型確認"],
    "click_html_alert": ["HTML", "ダイアログ", "クリック"],
    "click_html_element": ["HTML", "クリック", "Web操作"],
    "click_mouse": ["マウス", "クリック", "基本操作"],
    "click_uia_element": ["UIオートメーション", "クリック", "Windows"],
    "close_browser": ["ブラウザ", "終了", "リソース管理"],
    "close_excel_book": ["Excel", "終了", "リソース管理"],
    "compare_dates_and_branch": ["分岐", "日付", "比較"],
    "compare_numbers_and_branch": ["分岐", "数値", "比較"],
    "compare_strings_and_branch": ["分岐", "文字列", "比較"],
    "compress_file_or_directory": ["ファイル", "圧縮", "アーカイブ"],
    "continue_loop": ["ループ", "制御", "継続"],
    "convert_character_type": ["文字列", "変換", "全角半角"],
    "convert_date_format": ["日付", "変換", "フォーマット"],
    "copy_excel_range": ["Excel", "コピー", "クリップボード"],
    "copy_file_or_directory": ["ファイル", "コピー", "基本操作"],
    "copy_paste_spreadsheet": ["スプレッドシート", "コピー", "貼り付け"],
    "copy_spreadsheet_sheet": ["スプレッドシート", "シート", "コピー"],
    "copy_to_clipboard": ["クリップボード", "コピー", "データ転送"],
    "create_directory": ["ファイル", "フォルダ", "作成"],
    "create_excel_sheet": ["Excel", "シート", "作成"],
    "create_spreadsheet": ["スプレッドシート", "作成", "クラウド"],
    "create_spreadsheet_sheet": ["スプレッドシート", "シート", "作成"],
    "decompress_file": ["ファイル", "解凍", "アーカイブ"],
    "delete_excel_range": ["Excel", "削除", "セル操作"],
    "delete_excel_sheet": ["Excel", "シート", "削除"],
    "delete_file_or_directory": ["ファイル", "削除", "基本操作"],
    "delete_spreadsheet": ["スプレッドシート", "削除", "クラウド"],
    "delete_spreadsheet_range": ["スプレッドシート", "削除", "セル操作"],
    "delete_spreadsheet_sheet": ["スプレッドシート", "シート", "削除"],
    "download_html_csv": ["HTML", "ダウンロード", "CSV"],
    "download_html_element": ["HTML", "ダウンロード", "画像"],
    "drag_and_drop_to_absolute_coordinates": ["マウス", "ドラッグ", "座標"],
    "drag_and_drop_to_image": ["マウス", "ドラッグ", "画像認識"],
    "drag_and_drop_to_relative_coordinates": ["マウス", "ドラッグ", "相対座標"],
    "escape_html_iframe": ["HTML", "iframe", "フレーム操作"],
    "extract_fname": ["文字列", "パス", "抽出"],
    "find_image_and_branch": ["画像認識", "分岐", "検索"],
    "find_newest_file_from_fixed_directory": ["ファイル", "検索", "最新"],
    "focus_html_element": ["HTML", "フォーカス", "Web操作"],
    "focus_window": ["ウィンドウ", "切り替え", "フォーカス"],
    "focus_window_by_name": ["ウィンドウ", "切り替え", "名前指定"],
    "get_excel_address": ["Excel", "取得", "セル情報"],
    "get_excel_last_column": ["Excel", "取得", "最終列"],
    "get_excel_last_row": ["Excel", "取得", "最終行"],
    "get_excel_sheet_name": ["Excel", "取得", "シート名"],
    "get_excel_values": ["Excel", "取得", "値"],
    "get_json_values": ["JSON", "取得", "データ処理"],
    "get_spreadsheet_last_row": ["スプレッドシート", "取得", "最終行"],
    "get_spreadsheet_sheet_name": ["スプレッドシート", "取得", "シート名"],
    "get_spreadsheet_url": ["スプレッドシート", "取得", "URL"],
    "get_spreadsheet_values": ["スプレッドシート", "取得", "値"],
    "get_text_from_uia_element": ["UIオートメーション", "取得", "テキスト"],
    "get_uia_element_clickable_point": ["UIオートメーション", "取得", "座標"],
    "get_window_title": ["ウィンドウ", "取得", "タイトル"],
    "group_commands": ["制御", "グループ", "組織化"],
    "inherit_browsers": ["継承", "ブラウザ", "親シナリオ"],
    "inherit_excel": ["継承", "Excel", "親シナリオ"],
    "inherit_passwords": ["継承", "パスワード", "親シナリオ"],
    "inherit_variables": ["継承", "変数", "親シナリオ"],
    "inherit_windows": ["継承", "ウィンドウ", "親シナリオ"],
    "insert_excel_range": ["Excel", "挿入", "セル操作"],
    "insert_spreadsheet_range": ["スプレッドシート", "挿入", "行列操作"],
    "loop_by_line": ["ループ", "テキスト", "行処理"],
    "loop_csv": ["ループ", "CSV", "データ処理"],
    "loop_directory_contents": ["ループ", "ファイル", "フォルダ"],
    "loop_excel_col": ["ループ", "Excel", "列処理"],
    "loop_excel_row": ["ループ", "Excel", "行処理"],
    "loop_n_times": ["ループ", "回数指定", "基本"],
    "loop_spreadsheet_col": ["ループ", "スプレッドシート", "列処理"],
    "loop_spreadsheet_row": ["ループ", "スプレッドシート", "行処理"],
    "maximize_focused_window": ["ウィンドウ", "最大化", "サイズ変更"],
    "move_excel_sheet": ["Excel", "シート", "移動"],
    "move_fixed_file_to_fixed_directory": ["ファイル", "移動", "基本操作"],
    "move_mouse_to_absolute_coordinates": ["マウス", "移動", "座標"],
    "move_mouse_to_image": ["マウス", "移動", "画像認識"],
    "move_mouse_to_relative_coordinates": ["マウス", "移動", "相対座標"],
    "move_spreadsheet_sheet": ["スプレッドシート", "シート", "移動"],
    "offset_excel_range": ["Excel", "範囲", "オフセット"],
    "open_fixed_directory_name": ["ファイル", "フォルダ", "開く"],
    "open_static_file_name": ["ファイル", "開く", "アプリ起動"],
    "parse_brackets": ["文字列", "抽出", "括弧"],
    "parse_break_and_space": ["文字列", "整形", "空白除去"],
    "parse_delimiters": ["文字列", "抽出", "区切り文字"],
    "parse_regex": ["文字列", "抽出", "正規表現"],
    "paste_excel_range": ["Excel", "貼り付け", "クリップボード"],
    "pause": ["制御", "待機", "基本"],
    "pause_and_ask_to_proceed": ["制御", "確認", "インタラクティブ"],
    "pause_and_countdown_to_proceed": ["制御", "タイマー", "確認"],
    "play_sound": ["通知", "音声", "アラート"],
    "prepend_date_to_variable_filename": ["ファイル", "命名", "日付"],
    "prepend_string_to_variable_filename": ["ファイル", "命名", "文字列"],
    "prepend_variable_to_file": ["ファイル", "命名", "変数"],
    "raise_error": ["エラー処理", "テスト", "デバッグ"],
    "read_file": ["ファイル", "読み込み", "テキスト"],
    "receive_emails": ["メール", "受信", "ループ"],
    "receive_emails_gmail": ["メール", "Gmail", "受信"],
    "receive_emails_microsoft": ["メール", "Microsoft", "受信"],
    "remember_focused_browser_window": ["ブラウザ", "記憶", "ウィンドウ"],
    "remember_focused_window": ["ウィンドウ", "記憶", "参照"],
    "remember_named_window": ["ウィンドウ", "記憶", "名前指定"],
    "remember_open_excel_book": ["Excel", "記憶", "参照"],
    "remember_spreadsheet": ["スプレッドシート", "記憶", "参照"],
    "rename_excel_sheet": ["Excel", "シート", "名前変更"],
    "rename_file_or_directory": ["ファイル", "名前変更", "基本操作"],
    "rename_spreadsheet": ["スプレッドシート", "名前変更", "基本操作"],
    "rename_spreadsheet_sheet": ["スプレッドシート", "シート", "名前変更"],
    "replace_strings": ["文字列", "置換", "変換"],
    "retrieve_attribute_of_html_element": ["HTML", "取得", "属性"],
    "retrieve_link_of_html_element": ["HTML", "取得", "リンク"],
    "retrieve_src_of_html_element": ["HTML", "取得", "画像ソース"],
    "retrieve_text_of_html_alert": ["HTML", "取得", "アラート"],
    "retrieve_text_of_html_element": ["HTML", "取得", "テキスト"],
    "run_browser": ["ブラウザ", "起動", "基本"],
    "run_browser_with_profile": ["ブラウザ", "起動", "プロファイル"],
    "run_excel": ["Excel", "起動", "ファイル操作"],
    "run_excel_macro": ["Excel", "マクロ", "VBA"],
    "run_executable": ["アプリ", "起動", "基本"],
    "run_executable_and_wait": ["アプリ", "起動", "待機"],
    "run_external_scenario_and_branch": ["シナリオ", "実行", "分岐"],
    "run_javascript_in_browser": ["ブラウザ", "JavaScript", "実行"],
    "save_excel_book": ["Excel", "保存", "ファイル操作"],
    "scroll_mouse": ["マウス", "スクロール", "基本操作"],
    "search_file_from_directory_and_branch": ["ファイル", "検索", "分岐"],
    "search_html_element_and_branch": ["HTML", "検索", "分岐"],
    "search_screen_and_branch": ["画像認識", "検索", "分岐"],
    "select_excel_range": ["Excel", "選択", "セル操作"],
    "send_email": ["メール", "送信", "基本"],
    "send_email_gmail": ["メール", "Gmail", "送信"],
    "send_email_microsoft": ["メール", "Microsoft", "送信"],
    "send_password_to_html_element": ["HTML", "パスワード", "入力"],
    "send_password_to_uia_element": ["UIオートメーション", "パスワード", "入力"],
    "send_text_to_html_element": ["HTML", "テキスト", "入力"],
    "send_text_to_uia_element": ["UIオートメーション", "テキスト", "入力"],
    "set_browser_cookie": ["ブラウザ", "Cookie", "設定"],
    "set_dropdown_html_element": ["HTML", "ドロップダウン", "選択"],
    "set_excel_values": ["Excel", "設定", "値"],
    "set_spreadsheet_values": ["スプレッドシート", "設定", "値"],
    "switch_excel_sheet": ["Excel", "シート", "切り替え"],
    "switch_html_iframe": ["HTML", "iframe", "切り替え"],
    "take_screenshot": ["スクリーンショット", "記録", "画像"],
    "type_hotkeys": ["キーボード", "ショートカット", "入力"],
    "type_html_hotkeys": ["HTML", "ショートカット", "キーボード"],
    "typewrite_all_string": ["キーボード", "入力", "貼り付け"],
    "typewrite_password": ["キーボード", "パスワード", "セキュリティ"],
    "typewrite_static_string": ["キーボード", "入力", "文字"],
    "visit_url": ["ブラウザ", "URL", "アクセス"],
    "visit_url_with_basic_auth": ["ブラウザ", "認証", "アクセス"],
    "write_file": ["ファイル", "書き込み", "テキスト"],
}


def get_tags(cmd: str) -> list:
    """
    コマンド名からタグリストを取得

    Args:
        cmd: コマンド名

    Returns:
        タグリスト（見つからない場合は空リスト）
    """
    return STEP_TAGS.get(cmd, [])