"""
RPAステップのタグ定義
各ステップの機能カテゴリーや用途を示すタグを提供
"""

# ステップタグの辞書
STEP_TAGS = {
    "abort": ["制御", "エラー処理", "終了"],
    "add-memo": ["ドキュメント", "デバッグ", "保守"],
    "align-focused-window": ["ウィンドウ", "UI操作", "配置"],
    "api-web": ["API", "データ連携", "Web"],
    "assign-arithmetic-result-to-string-variable-v2": ["変数", "計算", "数値処理"],
    "assign-clipboard-to-string-variable": ["変数", "クリップボード", "データ取得"],
    "assign-date-business-to-string-variable": ["変数", "日付", "営業日"],
    "assign-date-calculation-to-string-variable": ["変数", "日付", "計算"],
    "assign-date-to-string-variable": ["変数", "日付", "フォーマット"],
    "assign-date-weekdays-to-string-variable": ["変数", "日付", "曜日"],
    "assign-day-of-week-to-string-variable": ["変数", "日付", "曜日"],
    "assign-environment-variable": ["変数", "環境", "システム情報"],
    "assign-file-modification-timestamp-to-string-variable": ["変数", "ファイル", "タイムスタンプ"],
    "assign-file-size-to-string-variable": ["変数", "ファイル", "サイズ"],
    "assign-live-input-to-string-variable": ["変数", "入力", "インタラクティブ"],
    "assign-password-variable": ["変数", "セキュリティ", "パスワード"],
    "assign-random-number-to-string-variable": ["変数", "ランダム", "数値処理"],
    "assign-string-variable": ["変数", "基本", "データ保存"],
    "assign-time-calculation-to-string-variable": ["変数", "時刻", "計算"],
    "assign-timestamp-to-string-variable": ["変数", "時刻", "フォーマット"],
    "break-loop": ["ループ", "制御", "脱出"],
    "calculate-excel-column": ["Excel", "計算", "列操作"],
    "change-speed-for-command-execution": ["制御", "速度調整", "待機"],
    "check-for-errors": ["エラー処理", "制御", "リトライ"],
    "check-for-errors-2": ["エラー処理", "制御", "リトライ"],
    "check-html-checkbox-or-radiobutton": ["HTML", "フォーム", "状態確認"],
    "check-json-type": ["JSON", "データ処理", "型確認"],
    "click-html-alert": ["HTML", "ダイアログ", "クリック"],
    "click-html-element": ["HTML", "クリック", "Web操作"],
    "click-mouse": ["マウス", "クリック", "基本操作"],
    "click-uia-element": ["UIオートメーション", "クリック", "Windows"],
    "close-browser": ["ブラウザ", "終了", "リソース管理"],
    "close-excel-book": ["Excel", "終了", "リソース管理"],
    "compare-dates-and-branch": ["分岐", "日付", "比較"],
    "compare-numbers-and-branch": ["分岐", "数値", "比較"],
    "compare-strings-and-branch": ["分岐", "文字列", "比較"],
    "compress-file-or-directory": ["ファイル", "圧縮", "アーカイブ"],
    "continue-loop": ["ループ", "制御", "継続"],
    "convert-character-type": ["文字列", "変換", "全角半角"],
    "convert-date-format": ["日付", "変換", "フォーマット"],
    "copy-excel-range": ["Excel", "コピー", "クリップボード"],
    "copy-file-or-directory": ["ファイル", "コピー", "基本操作"],
    "copy-paste-spreadsheet": ["スプレッドシート", "コピー", "貼り付け"],
    "copy-spreadsheet-sheet": ["スプレッドシート", "シート", "コピー"],
    "copy-to-clipboard": ["クリップボード", "コピー", "データ転送"],
    "create-directory": ["ファイル", "フォルダ", "作成"],
    "create-excel-sheet": ["Excel", "シート", "作成"],
    "create-spreadsheet": ["スプレッドシート", "作成", "クラウド"],
    "create-spreadsheet-sheet": ["スプレッドシート", "シート", "作成"],
    "decompress-file": ["ファイル", "解凍", "アーカイブ"],
    "delete-excel-range": ["Excel", "削除", "セル操作"],
    "delete-excel-sheet": ["Excel", "シート", "削除"],
    "delete-file-or-directory": ["ファイル", "削除", "基本操作"],
    "delete-spreadsheet": ["スプレッドシート", "削除", "クラウド"],
    "delete-spreadsheet-range": ["スプレッドシート", "削除", "セル操作"],
    "delete-spreadsheet-sheet": ["スプレッドシート", "シート", "削除"],
    "download-html-csv": ["HTML", "ダウンロード", "CSV"],
    "download-html-element": ["HTML", "ダウンロード", "画像"],
    "drag-and-drop-to-absolute-coordinates": ["マウス", "ドラッグ", "座標"],
    "drag-and-drop-to-image": ["マウス", "ドラッグ", "画像認識"],
    "drag-and-drop-to-relative-coordinates": ["マウス", "ドラッグ", "相対座標"],
    "escape-html-iframe": ["HTML", "iframe", "フレーム操作"],
    "extract-fname": ["文字列", "パス", "抽出"],
    "find-image-and-branch": ["画像認識", "分岐", "検索"],
    "find-newest-file-from-fixed-directory": ["ファイル", "検索", "最新"],
    "focus-html-element": ["HTML", "フォーカス", "Web操作"],
    "focus-window": ["ウィンドウ", "切り替え", "フォーカス"],
    "focus-window-by-name": ["ウィンドウ", "切り替え", "名前指定"],
    "get-excel-address": ["Excel", "取得", "セル情報"],
    "get-excel-last-column": ["Excel", "取得", "最終列"],
    "get-excel-last-row": ["Excel", "取得", "最終行"],
    "get-excel-sheet-name": ["Excel", "取得", "シート名"],
    "get-excel-values": ["Excel", "取得", "値"],
    "get-json-values": ["JSON", "取得", "データ処理"],
    "get-spreadsheet-last-row": ["スプレッドシート", "取得", "最終行"],
    "get-spreadsheet-sheet-name": ["スプレッドシート", "取得", "シート名"],
    "get-spreadsheet-url": ["スプレッドシート", "取得", "URL"],
    "get-spreadsheet-values": ["スプレッドシート", "取得", "値"],
    "get-text-from-uia-element": ["UIオートメーション", "取得", "テキスト"],
    "get-uia-element-clickable-point": ["UIオートメーション", "取得", "座標"],
    "get-window-title": ["ウィンドウ", "取得", "タイトル"],
    "group-commands": ["制御", "グループ", "組織化"],
    "inherit-browsers": ["継承", "ブラウザ", "親シナリオ"],
    "inherit-excel": ["継承", "Excel", "親シナリオ"],
    "inherit-passwords": ["継承", "パスワード", "親シナリオ"],
    "inherit-variables": ["継承", "変数", "親シナリオ"],
    "inherit-windows": ["継承", "ウィンドウ", "親シナリオ"],
    "insert-excel-range": ["Excel", "挿入", "セル操作"],
    "insert-spreadsheet-range": ["スプレッドシート", "挿入", "行列操作"],
    "loop-by-line": ["ループ", "テキスト", "行処理"],
    "loop-csv": ["ループ", "CSV", "データ処理"],
    "loop-directory-contents": ["ループ", "ファイル", "フォルダ"],
    "loop-excel-col": ["ループ", "Excel", "列処理"],
    "loop-excel-row": ["ループ", "Excel", "行処理"],
    "loop-n-times": ["ループ", "回数指定", "基本"],
    "loop-spreadsheet-col": ["ループ", "スプレッドシート", "列処理"],
    "loop-spreadsheet-row": ["ループ", "スプレッドシート", "行処理"],
    "maximize-focused-window": ["ウィンドウ", "最大化", "サイズ変更"],
    "move-excel-sheet": ["Excel", "シート", "移動"],
    "move-fixed-file-to-fixed-directory": ["ファイル", "移動", "基本操作"],
    "move-mouse-to-absolute-coordinates": ["マウス", "移動", "座標"],
    "move-mouse-to-image": ["マウス", "移動", "画像認識"],
    "move-mouse-to-relative-coordinates": ["マウス", "移動", "相対座標"],
    "move-spreadsheet-sheet": ["スプレッドシート", "シート", "移動"],
    "offset-excel-range": ["Excel", "範囲", "オフセット"],
    "open-fixed-directory-name": ["ファイル", "フォルダ", "開く"],
    "open-static-file-name": ["ファイル", "開く", "アプリ起動"],
    "parse-brackets": ["文字列", "抽出", "括弧"],
    "parse-break-and-space": ["文字列", "整形", "空白除去"],
    "parse-delimiters": ["文字列", "抽出", "区切り文字"],
    "parse-regex": ["文字列", "抽出", "正規表現"],
    "paste-excel-range": ["Excel", "貼り付け", "クリップボード"],
    "pause": ["制御", "待機", "基本"],
    "pause-and-ask-to-proceed": ["制御", "確認", "インタラクティブ"],
    "pause-and-countdown-to-proceed": ["制御", "タイマー", "確認"],
    "play-sound": ["通知", "音声", "アラート"],
    "prepend-date-to-variable-filename": ["ファイル", "命名", "日付"],
    "prepend-string-to-variable-filename": ["ファイル", "命名", "文字列"],
    "prepend-variable-to-file": ["ファイル", "命名", "変数"],
    "raise-error": ["エラー処理", "テスト", "デバッグ"],
    "read-file": ["ファイル", "読み込み", "テキスト"],
    "receive-emails": ["メール", "受信", "ループ"],
    "receive-emails-gmail": ["メール", "Gmail", "受信"],
    "receive-emails-microsoft": ["メール", "Microsoft", "受信"],
    "remember-focused-browser-window": ["ブラウザ", "記憶", "ウィンドウ"],
    "remember-focused-window": ["ウィンドウ", "記憶", "参照"],
    "remember-named-window": ["ウィンドウ", "記憶", "名前指定"],
    "remember-open-excel-book": ["Excel", "記憶", "参照"],
    "remember-spreadsheet": ["スプレッドシート", "記憶", "参照"],
    "rename-excel-sheet": ["Excel", "シート", "名前変更"],
    "rename-file-or-directory": ["ファイル", "名前変更", "基本操作"],
    "rename-spreadsheet": ["スプレッドシート", "名前変更", "基本操作"],
    "rename-spreadsheet-sheet": ["スプレッドシート", "シート", "名前変更"],
    "replace-strings": ["文字列", "置換", "変換"],
    "retrieve-attribute-of-html-element": ["HTML", "取得", "属性"],
    "retrieve-link-of-html-element": ["HTML", "取得", "リンク"],
    "retrieve-src-of-html-element": ["HTML", "取得", "画像ソース"],
    "retrieve-text-of-html-alert": ["HTML", "取得", "アラート"],
    "retrieve-text-of-html-element": ["HTML", "取得", "テキスト"],
    "run-browser": ["ブラウザ", "起動", "基本"],
    "run-browser-with-profile": ["ブラウザ", "起動", "プロファイル"],
    "run-excel": ["Excel", "起動", "ファイル操作"],
    "run-excel-macro": ["Excel", "マクロ", "VBA"],
    "run-executable": ["アプリ", "起動", "基本"],
    "run-executable-and-wait": ["アプリ", "起動", "待機"],
    "run-external-scenario-and-branch": ["シナリオ", "実行", "分岐"],
    "run-javascript-in-browser": ["ブラウザ", "JavaScript", "実行"],
    "save-excel-book": ["Excel", "保存", "ファイル操作"],
    "scroll-mouse": ["マウス", "スクロール", "基本操作"],
    "search-file-from-directory-and-branch": ["ファイル", "検索", "分岐"],
    "search-html-element-and-branch": ["HTML", "検索", "分岐"],
    "search-screen-and-branch": ["画像認識", "検索", "分岐"],
    "select-excel-range": ["Excel", "選択", "セル操作"],
    "send-email": ["メール", "送信", "基本"],
    "send-email-gmail": ["メール", "Gmail", "送信"],
    "send-email-microsoft": ["メール", "Microsoft", "送信"],
    "send-password-to-html-element": ["HTML", "パスワード", "入力"],
    "send-password-to-uia-element": ["UIオートメーション", "パスワード", "入力"],
    "send-text-to-html-element": ["HTML", "テキスト", "入力"],
    "send-text-to-uia-element": ["UIオートメーション", "テキスト", "入力"],
    "set-browser-cookie": ["ブラウザ", "Cookie", "設定"],
    "set-dropdown-html-element": ["HTML", "ドロップダウン", "選択"],
    "set-excel-values": ["Excel", "設定", "値"],
    "set-spreadsheet-values": ["スプレッドシート", "設定", "値"],
    "switch-excel-sheet": ["Excel", "シート", "切り替え"],
    "switch-html-iframe": ["HTML", "iframe", "切り替え"],
    "take-screenshot": ["スクリーンショット", "記録", "画像"],
    "type-hotkeys": ["キーボード", "ショートカット", "入力"],
    "type-html-hotkeys": ["HTML", "ショートカット", "キーボード"],
    "typewrite-all-string": ["キーボード", "入力", "貼り付け"],
    "typewrite-password": ["キーボード", "パスワード", "セキュリティ"],
    "typewrite-static-string": ["キーボード", "入力", "文字"],
    "visit-url": ["ブラウザ", "URL", "アクセス"],
    "visit-url-with-basic-auth": ["ブラウザ", "認証", "アクセス"],
    "write-file": ["ファイル", "書き込み", "テキスト"],
}


def get_tags(cmd: str) -> list:
    """
    コマンド名からタグリストを取得

    Args:
        cmd: コマンド名

    Returns:
        タグリスト（見つからない場合は空リスト）
    """
    return STEP_TAGS.get(cmd, [])